import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import MyFooter from "@/components/MyFooter";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"], 
  weight: ["400", "500", "700"], // 可选权重
  variable: "--font-jetbrains-mono", // CSS 变量
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={jetBrainsMono.variable}
      >
      <Navbar />
     
      <main>{children}</main>
      <MyFooter />
      </body>
    </html>
  );
}
